export const CATEGORIES=["Akidah","Bahasa Arab","Fiqih","Tajwid","Tahfidz","Al-Qur'an & Hadis"] as const;export type Category=typeof CATEGORIES[number];
export const THEMES=["Mobil Balap & Truk Konstruksi","Pesawat Terbang & Jet","Kereta Api Cepat & Rel","Blok Kayu Edukasi & Meja Belajar","Pemandangan Alam & Arsitektur Masjid Minimalis"] as const;export type Theme=typeof THEMES[number];
export const STYLES=["3D Cute Isometric Clay","Flat Vector Infographic","Clean LEGO Style Bricks"] as const;export type Style=typeof STYLES[number];
export const MOODS=["Cerah Ceria","Lembut Pastel","Minimalis Islami"] as const;export type Mood=typeof MOODS[number];
export const FORBIDDEN=["human","humans","person","people","man","woman","men","women","boy","girl","child","children","kid","kids","face","faces","eyes","hand","hands","animal","animals","bird","birds","insect","insects","living creature","living creatures","character","characters","mascot","mascots","statue","statues","idol","idols","cross","crosses"] as const;
export const NEGATIVE=[...FORBIDDEN,"photographic depiction of souls","blurry","low quality","distorted shapes","cluttered background","text errors","misspelled words"].join(", ");
const SAFETY="Inanimate objects only, absolutely no people, no living beings, no faces or eyes on any object, empty scene with no characters";
const DATA:Record<Theme,[string,string,string]>={"Mobil Balap & Truk Konstruksi":["colorful toy race cars and construction trucks","toy cars aligned in perfectly straight rows","an empty toy garage floor"],"Pesawat Terbang & Jet":["toy passenger airplanes and sleek jets","toy airplanes arranged in precise parallel rows","an empty miniature runway"],"Kereta Api Cepat & Rel":["toy high-speed trains and railway tracks","numbered train carriages connected in exact order","an empty miniature railway platform"],"Blok Kayu Edukasi & Meja Belajar":["wooden educational blocks and a tidy study desk","numbered wooden blocks arranged in exact order","a clean empty study desk"],"Pemandangan Alam & Arsitektur Masjid Minimalis":["minimalist mosque architecture and natural landscape","empty prayer mats aligned precisely in straight rows","a serene empty mosque and landscape"]};
export const TEMPLATES=[{id:"imam",label:"Hadits Urutan Imam Salat",lesson:"Hadits tentang urutan imam salat: yang paling fasih bacaan Al-Qur'annya, lalu yang paling paham sunnah, lalu yang lebih dahulu hijrah, lalu yang lebih tua.",category:"Fiqih" as Category,theme:"Mobil Balap & Truk Konstruksi" as Theme},{id:"rukun",label:"Rukun Islam",lesson:"Lima Rukun Islam secara berurutan: syahadat, salat, zakat, puasa Ramadan, dan haji bagi yang mampu.",category:"Akidah" as Category,theme:"Blok Kayu Edukasi & Meja Belajar" as Theme},{id:"makan",label:"Adab Makan",lesson:"Adab makan: membaca bismillah, makan dengan tangan kanan, makan yang terdekat, tidak berlebihan, dan mengucap hamdalah setelah selesai.",category:"Adab Sehari-hari" as Category,theme:"Kereta Api Cepat & Rel" as Theme}];
export function sanitizeLesson(value:string){const s=value.replace(/\s+/g," ").trim();const pattern=FORBIDDEN.map(x=>x.split(" ").join("\\s+")).join("|");return s.replace(new RegExp("\\b(?:"+pattern+")\\b","gi"),"inanimate educational concept")}
export function validateInput(lesson:string){return lesson.trim()?{ok:true as const}:{ok:false as const,message:"Materi pelajaran belum diisi. Tulis ringkasan materi terlebih dahulu."}}
const ordered=(s:string)=>/\b(urutan|berurutan|langkah|tahap|rukun|pertama|kedua|ketiga|lalu|kemudian|order|step|steps|sequence)\b/i.test(s);
export function generatePrompt(i:{lesson:string;category:Category;theme:Theme;style:Style;mood:Mood}){const safe=sanitizeLesson(i.lesson);const d=DATA[i.theme];const concept=i.category==="Akidah"?"clear foundational beliefs presented in an orderly educational concept":i.category==="Bahasa Arab"?"Arabic vocabulary and language concepts presented clearly and in sequence":i.category==="Fiqih"?"Islamic rulings and practical worship concepts presented in an orderly educational concept":i.category==="Tajwid"?"Quran recitation rules and letter/sound relationships presented clearly":i.category==="Tahfidz"?"memorization sequence, repetition, and organized Quran study concepts":"Quran and hadith knowledge presented as an orderly educational concept";const visual=ordered(safe)?"numbered "+d[0]+" arranged in exact sequence":d[1];const st=i.style==="3D Cute Isometric Clay"?"cute 3D isometric clay style":i.style==="Flat Vector Infographic"?"flat vector infographic style":"clean plastic building-brick diorama style";return{positive:"Educational illustration for children about \""+safe+"\". Concept: "+concept+", visualized as "+visual+". Setting: "+d[2]+". Style: "+st+". Colors: "+i.mood+". "+SAFETY+". Composition: centered, uncluttered, clear focal point, sharp focus, high detail.",negative:NEGATIVE}}